Exploratory Data Analysis :: Project 02
==========
### By Felipe Campelo

### Plot 1
Question: *Have total emissions from $PM_{2.5}$ decreased in the United States from 1999 to 2008? Using the base plotting system, make a plot showing the total $PM_{2.5}$ emission from all sources for each of the years 1999, 2002, 2005, and 2008.*

Check **plot1.R** and **plot1.png** for these answers.

### Plot 2
Question: *Have total emissions from PM2.5 decreased in the Baltimore City, Maryland 
(fips == "24510") from 1999 to 2008? Use the base plotting system to make a plot 
answering this question.*

Check **plot2.R** and **plot2.png** for these answers.

### Plot 3
Question: *Of the four types of sources indicated by the type (point, nonpoint, onroad, nonroad) variable, which of these four sources have seen decreases in emissions from 1999–2008 for Baltimore City? Which have seen increases in emissions from 1999–2008? Use the ggplot2 plotting system to make a plot answer this question.*

Check **plot3.R** and **plot3.png** for these answers.

### Plot 4
Question: *Across the United States, how have emissions from coal combustion-related sources changed from 1999–2008?*

Check **plot4.R** and **plot4.png** for these answers.